version: '3'

services:
  mysql-db:
    image: mysql:8.0
    container_name: orders-service-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: ${DATABASE} 
    ports:
      - "3306:3306" 
    volumes:
      - mysql_data:/var/lib/mysql 
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped

  orders-service-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: orders-service-app  
    container_name: orders-service-container
    ports:
      - "3007:3007" 
    environment:
      HOST: mysql-db            
      DB_PORT: 3306             
      USERNAME: ${USERNAME}             
      PASSWORD: ${PASSWORD}        
      DATABASE: ${DATABASE}    
      PORT: 3007
      GAMES_ENDPOINT: ${GAMES_ENDPOINT}
    depends_on:
      - mysql-db
    volumes:
      - .:/app 
      - /app/node_modules
    restart: unless-stopped

volumes:
  mysql_data: